autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

overrides:
  # eslint: ">=10.0.0"
  # '@eslint/js': ">=10.0.0"
  eslint: "^9"
  '@eslint/js': "^9"
  '@stylistic/eslint-plugin': '>=5.0.0'

strictPeerDependencies: false
