name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Use Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 'lts/*'
        check-latest: true
        package-manager-cache: false

    - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      name: Install pnpm
      id: pnpm-install
      with:
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]

    - name: Setup Swift
      run: |
        curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz && \
        tar zxf swiftly-$(uname -m).tar.gz && \
        ./swiftly init --quiet-shell-followup && \
        . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh" && \
        hash -r
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

    - name: format (swift)
      run: swift format format -rip Soureces

    - name: lint (swift)
      run: swift format lint -rp Soureces

    - name: Build Handler
      run: swift package archive --allow-network-connections docker --runtime provided.al2023

    - name: lint
      run: pnpm lint

    - name: build
      run: pnpm build
